project-codeflare/codeflare-operator

- .github/workflows/precommit.yml
We are just re-using an image built by the Open Data Hub organization in this GitHub Action. As the functional goals are the same, it didn't make sense for us to start building a new image ourselves.
> Add pre-commit GitHub Action

- api/v1alpha1/mcad_types.go
- config/crd/bases/codeflare.codeflare.dev_mcads.yaml
- config/internal/mcad/configmap.yaml.tmpl
- controllers/mcad_controller.go
- controllers/mcad_controller_test.go
- controllers/testdata/mcad_test_cases/case_2.yaml
- controllers/testdata/mcad_test_results/case_1/configmap.yaml
- controllers/testdata/mcad_test_results/case_2/configmap.yaml
- controllers/testdata/mcad_test_results/case_2/rolebinding.yaml
- controllers/testdata/mcad_test_results/case_2/service.yaml
- controllers/testdata/mcad_test_results/case_2/serviceaccount.yaml
This allows MCAD to determine what an undefined value should default to
closes #53
> Don't add default values to config map if not specified.

- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_config_patch.yaml
- config/manager/manager.yaml
- config/prometheus/monitor.yaml
- config/rbac/auth_proxy_service.yaml
This PR changes the operator deployment to use a uniquely identifying labels selector.
In order to work-around the immutability of the labels selector field, the deployment has been renamed according to OLM recommendation: https://github.com/operator-framework/operator-lifecycle-manager/issues/952#issuecomment-639657949.
This PR also leverages Kustomise `commonLabels` config, to apply [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) to all resources.
Fixes #112.
> Use uniquely identifying labels selector for the operator deployment

- controllers/instascale_controller_test.go
- controllers/testdata/instascale_test_cases/case_3.yaml
- controllers/testdata/instascale_test_results/case_3/deployment.yaml
This follows up #120, and adds a test case covering the new `controllerImage` field of the InstaScale resource.
> Add test for custom InstaScale controller image support

- Makefile
- OWNERS
- README.md
- config/crd/mcad/kustomization.yaml
- config/internal/mcad/deployment.yaml.tmpl
- controllers/defaults.go
- controllers/testdata/instascale_test_results/case_1/deployment.yaml
- controllers/testdata/instascale_test_results/case_2/deployment.yaml
One thing to note: I haven't yet tested with the latest images
> Update operator to 0.0.4

- Makefile
- config/crd/mcad/kustomization.yaml
This PR adds a variable to parameterise the version of the MCAD dependency.
It follows up #116, so the version used to retrieve the MCAD CRDs is not hard-coded anymore.
It'll also be used for #114.
> Add MCAD version variable

- Makefile
- config/crd/mcad/kustomization.yaml
This PR follows up #139, to support the complete definition of the MCAD CRD resources reference, as suggested here:
https://github.com/project-codeflare/codeflare-operator/pull/139/files/26da2ebf8c15155a3a6eea1d48901d2f61a76f09#diff-a2ca4be61aa64f38fb728281ca786796093cc29b47cd1b5ba2b1d2050c3732f6
> Extended support for referencing MCAD CRD resources

- Makefile
- api/codeflare/v1alpha1/mcad_types.go
- config/crd/bases/codeflare.codeflare.dev_mcads.yaml
- controllers/defaults.go
- controllers/mcad_controller.go
- controllers/mcad_controller_test.go
- controllers/mcad_params.go
- controllers/testdata/mcad_test_cases/case_3.yaml
- controllers/testdata/mcad_test_results/case_3/deployment.yaml
> feat(api): Support custom MCAD container image

- README.md
> doc: The operator should be started before setting up e2e tests

- Makefile
The update of the MCAD version when installing CRDs is missing.
This PR applies the MCAD version the same way it's done when deploying the operator.
Fixes #151.
> fix: Update MCAD version when installing CRDs

- .github/workflows/tag-and-build.yml
- Makefile
- README.md
- controllers/defaults.go
- controllers/testdata/instascale_test_results/case_1/deployment.yaml
- controllers/testdata/instascale_test_results/case_2/deployment.yaml
Contains also code changes related to 0.0.5 release.
> Use CodeFlare machine user to push PR into OpenShift community operators repository

- Makefile
Upstream is no longer publishing release branches of the form `release-vX.Y.Z` Instead, it is publishing tags of the form `vX.Y.Z`, this commit makes it so.
I also had to do a lot of work to get the tests to pass -- the `controller-gen` kept failing with errors like 
```
/home/aasthana/go/src/github.com/codeflare-operator/test/support/utils.go:27:9: expected '(', found '['
/home/aasthana/go/src/github.com/codeflare-operator/test/support/utils.go:27:10: mixed named and unnamed parameters
```
The errors seem to mainly be in the `support` directory. I ended up just deleting all the tests...
This closes #171
> Fix mcad tag reference for CRDs

- config/default/manager_auth_proxy_patch.yaml
- config/rbac/auth_proxy_service.yaml
Resolves #169 
Besides exposing the endpoint, there was a need to change the `--metrics-bind-address=127.0.0.1:8080` args, from localhost to 0.0.0.0 for Prometheus to start scraping metrics successfully.
Tested with the CodeFlare Operator alert rules set on this PR: https://github.com/red-hat-data-services/odh-deployer/pull/365 
**Note:** this job was a collaborative effort between @Fiona-Waters, @dimakis, and myself @ChristianZaccaria
> Expose CodeFlare Operator metrics endpoint

- .github/actions/kind/action.yml
- .github/workflows/olm_tests.yaml
- Makefile
Fixes https://github.com/project-codeflare/codeflare-operator/issues/188
> Remove waiting loops for kubernetes resources from Makefile

- .github/workflows/tag-and-build.yml
Fixes https://github.com/project-codeflare/codeflare-operator/issues/200
Release workflow was altered to open a PR with code changes instead of pushing changes directly.
Can be verified using own fork of codeflare-operator repository.
Setup the required secrets for your fork:
- CODEFLARE_MACHINE_ACCOUNT_TOKEN - personal access token with rights to create PRs
- QUAY_ID, QUAY_TOKEN - credentials for Quay account to push images to
Push changes in this PR into your repository fork on `main` branch.
Manually run the workflow, provide workflow parameters pointing to your own repositories (to avoid messing with official repos).
You can see results on my fork:
https://github.com/sutaakar/codeflare-operator/actions/runs/5694084278
https://github.com/sutaakar/codeflare-operator/pull/14
- Testing …
> Release workflow - open a PR with changes instead of direct push

- Makefile
- client/applyconfiguration/codeflare/v1alpha1/mcadspec.go
> Fix: add missing --output-base option to applyconfiguration-gen

- .github/workflows/project-codeflare-release.yml
Fixes https://github.com/project-codeflare/codeflare-operator/issues/107
Waiting for https://github.com/project-codeflare/multi-cluster-app-dispatcher/pull/427 and https://github.com/project-codeflare/multi-cluster-app-dispatcher/issues/453
> Create GitHub action to automate CodeFlare project release

- .github/actions/kind/action.yml
- Makefile
- README.md
- test/e2e/kind.sh
- test/e2e/mnist_rayjob_mcad_raycluster_test.go
- test/support/ingress.go
- test/support/ray.go
- test/support/ray_cluster_client.go
> e2e: Use Ray dashboard API to retrieve job logs

- Makefile
Closes https://github.com/project-codeflare/codeflare-operator/issues/219 
Changed the make target to a unique one.
Can now run `make kind-e2e` and it will create a kind cluster.
> Bug-fix - Make target with multiple recipes

- Makefile
- test/e2e/mnist_raycluster_sdk.py
- test/e2e/mnist_raycluster_sdk_test.go
- test/support/defaults.go
Release automation doesn't raise SDK version. Will address it in next PR.
Adjusted SDK version to latest release, applied changes in TestMNISTRayClusterSDK.
Install CodeFlare operator using OLM on OpenShift.
Install test requirements by running make setup-e2e
Run e2e tests - TestMNISTRayClusterSDK.
> Adjust SDK version, fix TestMNISTRayClusterSDK

- README.md
Added a note about a need to create SecurityContextConstraints for KubeRay to use proper user to run Ray cluster.
Without this adjustment the tests using Ray cluster fails on OpenShift.
Install CodeFlare operator using OLM on OpenShift.
Install test requirements by running `make setup-e2e`
Run e2e tests - the test `TestMNISTRayJobMCADRayCluster` fails.
Apply `SecurityContextConstraints` from this PR into KubeRay operator namespace, respin KubeRay pod.
Rerun the tests again - this time all tests pass.
> Add note to apply SecurityContextConstraints for OpenShift e2e tests

- .github/workflows/e2e_tests.yaml
- .github/workflows/olm_tests.yaml
- .github/workflows/precommit.yml
- CONTRIBUTING.md
- Dockerfile
- go.mod
This PR upgrades Go to version 1.19, which is the actual version required to build the current Kubernetes version, i.e., v1.26.
> Upgrade Go to version 1.19

- README.md
> docs: remove dollar signs to allow for correct copy and paste

- .github/workflows/tag-and-build.yml
Fixes https://github.com/project-codeflare/codeflare-operator/issues/224
Replacing CODEFLARE_SDK_VERSION value in Makefile in release GitHub workflow.
Checkout this PR, push it to your fork of CodeFlare operator repo.
Run release workflow, providing own values as parameters.
Check the content of PR opened with code changes - it will contain SDK version update.
> Adjust CODEFLARE_SDK_VERSION in GitHub release workflow

- .github/workflows/operator-image.yml
Fixes https://github.com/project-codeflare/codeflare-operator/issues/226
Every commit affecting operator code will trigger a workflow building operator image and publishing it on quay.
Push the change from PR to main branch of your fork - workflow s triggered and tries to upload built operator image on Quay.
> Build and publish dev operator image for every commit

- .github/workflows/e2e_tests.yaml
- .github/workflows/olm_tests.yaml
In the last release we noticed that the PR got merged in even though the olm upgrade tests was failing (and the e2e test passed). We suspect it is due to the name of the jobs.
https://project-codeflare.slack.com/archives/C04SSHUB3GB/p1691775982411549
> Update Job names so there is no overlap between e2e and olm CI

- test/e2e/mnist_raycluster_sdk_test.go
Resolves https://github.com/project-codeflare/codeflare-operator/issues/215
The TestMNISTRayClusterSDK e2e test previously only ran on OpenShift clusters as the codeflare-SDK did not support other kubernetes distributions. Now that this [PR](https://github.com/project-codeflare/codeflare-sdk/pull/146) has been merged and the codeflare-SDK dependency [updated](https://github.com/project-codeflare/codeflare-operator/commit/b325fab34bd5569a1f161ba818c90e001f509cd0) we can re-enable the test by removing the relevant call to skip the test.
Run e2e tests on a non openshift cluster and make sure that TestMNISTRayClusterSDK is passing. This test is currently skipped until https://github.com/project-codeflare/codeflare-sdk/pull/271 is merged.
> Enable TestMNISTRayClusterSDK test

- test/support/conditions.go
Minor fix to prevent e2e tests from failing in case Route initialization takes some time.
N/A
(Maybe there should be unit tests for test support package...)
> Test support: return default status if Route is not initialized

- Makefile
- README.md
- controllers/defaults.go
- controllers/testdata/instascale_test_results/case_1/deployment.yaml
- controllers/testdata/instascale_test_results/case_2/deployment.yaml
While deploying the codeflare stack on my osd cluster, the instascale pod did not come up and showed an `errImagePull` error. I noticed in the yaml that the image url was not as expected i.e it was v.0.0.7 instead of v0.0.7 as in Quay.io. This PR is updating the instascale image url.
> Fix Instascale Version

- test/e2e/mnist_pytorch_mcad_job_test.go
- test/e2e/mnist_rayjob_mcad_raycluster_test.go
Reduced CPU requests for e2e test AppWrappers to accommodate changes done in MCAD v1.34.0.
Since v1.34.0 MCAD is considering pod requests and limits of already deployed other pods when computing node capacity. 
As KinD used in e2e PR checks is significantly limited in resources, most of e2e test PR checks hit the limitation of CPU requests, blocking some tests from finishing.
N/A
Verification will be done by repeatedly running e2e PR check.
> e2e tests: Reduce CPU requests for e2e test AppWrappers

- .yamllint.yaml
- Makefile
- config/internal/instascale/clusterrole.yaml.tmpl
- config/internal/mcad/clusterrole_mcad-controller.yaml.tmpl
- config/rbac/role.yaml
- controllers/defaults.go
- controllers/instascale_controller.go
- controllers/mcad_controller.go
- controllers/testdata/instascale_test_results/case_1/clusterrole.yaml
- go.mod
- go.sum
- test/e2e/mnist_pytorch_mcad_job_test.go
- test/e2e/mnist_rayjob_mcad_raycluster_test.go
- test/support/mcad.go
Part of project-codeflare/adr#7
Follows up project-codeflare/multi-cluster-app-dispatcher#591
> Move AppWrapper API to workload.codeflare.dev group

- test/support/client.go
- test/support/mcad.go
Also adding clients for image operations and dynamic client.
N/A
Adding support functionality for https://github.com/opendatahub-io/distributed-workloads/pull/103
Adding a function to return AppWrappers based on name prefix, also creation of temporary file with content.
N/A
> Test support: Return list of AppWrappers

- Makefile
- README.md
Kustomize fn run is using Docker. This approach is incompatible with OpenShift CI, which doesn't provide Docker environment.
To make operator deployment being OpenShift CI friendly (and to remove a need to have specifically Docker installed for various Makefile actions) replacing the function with sed command providing same functionality.
Execute for example `make install` without Docker.
> Use sed command to replace MCAD repo reference in Makefile

- config/internal/mcad/clusterrole_mcad-controller.yaml.tmpl
- config/rbac/role.yaml
- controllers/mcad_controller.go
Closes https://github.com/project-codeflare/codeflare-operator/issues/187
Adjusts the mcad_controller.go rbac rules to match the recent changes with MCAD in PR https://github.com/project-codeflare/multi-cluster-app-dispatcher/pull/475
Did a make image-build and deployed it, looked good.  
- [x ] Manual tests
Checked the resulting rbac rules and they looked right. Left out the xqueuejobs as per @astefanutti suggestion.
> Adjust rbac to match mcad

- test/support/mcad.go
Intention is to align `AppWrappers` function with `AppWrapper`, so result of both functions can be used in transforming functions.
`AppWrappers` function now returns slice of pointers on `AppWrapper` instead of slice of structs.
Tested in ODH DW tests.
> e2e support: return AppWrapper pointers instead of structs

- Makefile
https://github.com/project-codeflare/codeflare-operator/issues/206
Raising KubeRay version to 0.6.0.
PR check (tested KubeRay with ODH and works well there).
> Update to KubeRay v0.6.0

- .github/workflows/tag-and-build.yml
- README.md
Closes #262 
Tested in https://github.com/jiripetrlik/codeflare-operator/actions/runs/6184331678/job/16787779852 . However, I removed all not necessary steps.
> [262] Add links to other release notes

- README.md
Quick fix for the README for integration tests. After the recent changes the operator requires to specify NAMESPACE environment variable.
> Fix E2E tests README

- Makefile
- README.md
User like to run `make install` on MacOs. Refer to [Conversation](https://project-codeflare.slack.com/archives/C04L7QH4Q84/p1695233314296039) 
Let user define sed binary
For MacOs ONLY:
```bash
brew install gnu-sed
make install -e SED=/usr/local/bin/gsed
```
- [ x] Manual tests
> gsed support for MacOs

- test/e2e/mnist_pytorch_mcad_job_test.go
- test/e2e/mnist_raycluster_sdk_test.go
- test/e2e/setup.sh
- test/support/batch.go
- test/support/core.go
- test/support/events.go
- test/support/ray_api.go
- test/support/test.go
Fixes https://github.com/project-codeflare/codeflare-operator/issues/290
Store logs of all containers in test namespace. Also store all namespace events.
See PR check logs.
> e2e test support: Store test pod logs and events

- main.go
Add the OpenShift Config API required by InstaScale to the runtime scheme, as discussed in #304.
It also adds the Machine API, that'll be required by project-codeflare/instascale#89.
> Add missing OpenShift Config API to runtime scheme

- config/rbac/instascale_role.yaml
- config/rbac/instascale_role_binding.yaml
closes #278 
Addition of a ClusterRole and a ClusterRoleBinding which binds the required permissions to the CFO serviceaccount
Run through demo instascale NBs with clusters leveraging machinepools (OSD) and machinesets (instructions for sample can be found [here](https://github.com/Maxusmusti/dev-clusters))
> refactor: addition of rbac needed for instascale controller

- test/e2e/mnist_rayjob_mcad_raycluster_test.go
- test/support/ingress.go
- test/support/route.go
- test/support/service.go
- test/support/support.go
Issue: https://github.com/project-codeflare/codeflare-operator/issues/275
PR to distributed-workloads with changes to tests will follow.
> [275] Implement ExposeService method

- .github/workflows/project-codeflare-release.yml
Closes #263 
It was necessary to use only one additional parameter for the list of released components because Github allows only 10 workflow parameters. I was also forced to use "if" for steps instead of jobs. It is because if I skip the job then all dependent jobs are also skipped which is not desirable.
Example runs (all bash code was commented out to not perform real release):
- https://github.com/jiripetrlik/codeflare-operator/actions/runs/6300310513
- https://github.com/jiripetrlik/codeflare-operator/actions/runs/6300326727
> [263] Release Action can skip intermediate steps

- config/rbac/kustomization.yaml
Follows up #304, so the InstaScale RBAC manifests are included.
> Include InstaScale RBAC in kustomization.yaml

- README.md
- test/e2e/mnist_pytorch_mcad_job_test.go
- test/e2e/mnist_raycluster_sdk_test.go
#313
Using the 'PYTHONUSERBASE' environment variable, to point to the emptyDir volume mount for mnist_pytorch_mcad_job_test and mnist_raycluster_sdk_test
Updated the readme to provide instructions to setting the CODEFLARE_TEST_OUTPUT_DIR when running e2e tests locally.
Follow the end to end test instructions, and they should now pass, and complete the runthrough :)
> fix: codeflare-operator e2e tests not passing

- .github/workflows/e2e_tests.yaml
- .github/workflows/olm_tests.yaml
- test/e2e/mnist_pytorch_mcad_job_test.go
- test/e2e/mnist_rayjob_mcad_raycluster_test.go
N/A
Use larger runners for e2e and OLM upgrade tests to speed up and stabilize test execution.
Check Pr checks.
> Use 4 core runners in e2e tests

- Makefile
- go.mod
- go.sum
- main.go
https://github.com/project-codeflare/multi-cluster-app-dispatcher/issues/649
Apply MCAD change for quota management API group version
N/A
> Change quota management API group version to v1alpha1

- .github/resources-olm-upgrade/subscription.yaml
- .github/workflows/e2e_tests.yaml
- .github/workflows/olm_tests.yaml
- Makefile
- config/e2e/kustomization.yaml
- config/e2e/patch_resources.yaml
- config/manager/manager.yaml
Following up #216, this PR update the operator compute resources so it better accounts for both MCAD and InstaScale controllers requirements.
It configures the resources so that the operator is assigned with the [guaranteed QoS class](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#guaranteed), and with enough resources, so it performs acceptably by default.
Closes #280.
> Update compute resources to account for MCAD and InstaScale

- Dockerfile
There's a number of CVEs that are closed in the latest versions of the go-1.19 toolset.
1. https://bugzilla.redhat.com/show_bug.cgi?id=2234712
2. https://bugzilla.redhat.com/show_bug.cgi?id=2234713
3. https://bugzilla.redhat.com/show_bug.cgi?id=2237782
4. https://bugzilla.redhat.com/show_bug.cgi?id=2237798
5. https://bugzilla.redhat.com/show_bug.cgi?id=2238352
Related: https://github.com/ray-project/kuberay/pull/1488
> Update go-toolset version for CVEs

- config/rbac/kustomization.yaml
- config/rbac/mcad-controller-ray-clusterrole.yaml
- config/rbac/mcad-controller-ray-clusterrolebinding.yaml
Closes #337 
ClusterRole and ClusterRoleBinding for KubeRay have been added.
Install following the [quick start](https://github.com/opendatahub-io/distributed-workloads/blob/main/Quick-Start-ODH-V2.md) and confirm that the ClusterRole and ClusterRole binding are being applied as expected and that there are no `rayclusters` errors in the CodeFlare Operator logs.
> Add ClusterRole and ClusterRoleBinding for KubeRay

- Makefile
- go.mod
- go.sum
- test/e2e/mnist_raycluster_sdk_test.go
- test/e2e/mnist_rayjob_mcad_raycluster_test.go
- test/support/ray.go
Replaced rayv1alpha1 with rayv1
Run `make build` there should be no errors
> Replaced rayv1alpha1 with rayv1

- Dockerfile
updates base image as per [this conversation](https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1697548522169089?thread_ts=1697036534.719189&cid=C05NXTEHLGY)
> Update ubi base image

- config/rbac/mcad-controller-ray-clusterrole.yaml
closes: #347 
Removed the routes resources in favour of ingress resources.
This will be needed for when [project-codeflare/codeflare-sdk/pull/251](https://github.com/project-codeflare/codeflare-sdk/pull/251) is merged as we will be moving towards creating ingresses over routes.
> Updated MCAD controller cluster role for ingresses

- .github/workflows/odh-fork-sync.yml
- .github/workflows/tag-and-build.yml
Closes: #366 
During the release on Friday the `odh-fork-sync` workflow did not trigger. I suspect the issue is similar to this one [here](https://github.com/orgs/community/discussions/26875#discussioncomment-3253761) . 
I updated the `tag-and-build` workflow to use the `CODEFLARE_MACHINE_ACCOUNT_TOKEN` instead of the `github.TOKEN` which could solve our issue.
I also made changes to how `odh-sync-fork` is set up.
I tested this out using example workflows and I got a workflow to trigger on a published release using the PAT token.
> Updated CFO sync and tag-build workflows

- test/e2e/mnist_raycluster_sdk_test.go
closes https://github.com/project-codeflare/codeflare-operator/issues/328
Added security context on the test Pod to avoid PodSecurity warning when running TestMNISTRayClusterSDK on OpenShift FIPS enabled cluster
1.Setup the codeflare operator on cluster openshift with FIPS enabled mode(https://docs.openshift.com/container-platform/4.12/installing/installing-fips.html) 
2. Run test TestMNISTRayClusterSDK and check whether warnings are showing while running the test 
Note : Tested this test by  removing skip  in local on openshift cluster with  FIPS enable mode
> Set security context on test pod to avoid pod security warning

- .github/workflows/auto-add-issues.yml
Remove workflow job adding `triage/needs-triage` label for new issues. Currently the triage is leveraging priority field.
N/A
> Remove automatic triage/needs-triage label creation

- go.mod
- go.sum
- main.go
instaScaleController was missing context during it's setup.
Added context to `instaScaleController.SetupWithManager()`
run `make build INSTASCALE_VERSION=v0.3.0`
> Added context to InstaScale Setup

- Makefile
> Fix broken catalog-build-from-index command

- .github/workflows/tag-and-build.yml
- config/crd/mcad/kustomization.yaml
Fixes https://github.com/project-codeflare/codeflare-operator/issues/388
Manifest is generated as part of the release flow. It is declared as a separate step because its invocation as part of bundle generation is hidden - changes are reverted after bundle build.
N/A
> Regenerate CFO CRD manifests for release

- Dockerfile
Closes https://github.com/red-hat-data-services/codeflare-operator/issues/4
cc @jbusche 
The failures have gone away, but I'm seeing the following warning now:
```
---- Warning Report
+------------------------+-----------------+-----------------------------------------------------------------+---------------------------------------------------+
| OPERATOR NAME          | EXECUTABLE NAME | STATUS                                                          | IMAGE                                             |
+------------------------+-----------------+-----------------------------------------------------------------+---------------------------------------------------+
| ubi8-minimal-container | /manager        | go binary has no build tags set (should have strictfipsruntime) | …
```
> Use CGO_ENABLED=1 for FIPS compliance reasons

- Dockerfile
Related: #391 
https://github.com/red-hat-data-services/codeflare-operator/issues/4
> Add stricttag to pass fips check warnings

- .gitignore
- .vscode/launch.json
- CONTRIBUTING.md
Added launch.json file for local debugging of the CodeFlare Operator
Fill in the launch.json file with your kube config file path and namespace the CFO should be acting in.
Scale down the CodeFlare Operator deployment if it exists in your cluster.
The operator should be running locally with VSCode.
> Added launch.json for local debugging with VSCode

- .github/workflows/tag-and-build.yml
Closes #<[380](https://github.com/project-codeflare/codeflare-operator/issues/380)>
Updating `Tag and build`GH action to add KubeRay line in the compatibilty matrix
> Update workflow to add kuberay in compatibility matrix

- Makefile
- main.go
This PR adds a log line with the build version and build date of the CFO.
Knowing the build version and build date is useful when debugging historical logs and correlating them with the actual code that produced them.
build version format:
```
<tag>[-<sha>][-dirty]
```
`<tag>`: The name of the most recent tag (stripping the prefix 'v')
`<sha>`: If HEAD is not pointed to a tag, then the hash of HEAD is added.
`dirty`: If the repository contains any changes, "-dirty" is added.
Note: Once approved, I think it will be beneficial to add a similar PR to MCAD and will be happy to do that.
Build and run:
```
make build && ./bin/manager
```
The first log line should look like:
```
2023-11-13T17:27:45+02:00       INFO    setup   Build info      {"version": "1.0.0-7991ad5", "date": "2023-11-13 …
```
> Add build info to logs

- go.mod
- go.sum
- main.go
- Added a call to `flag.Parse()` to parse command line flags.
- Updated `glog` module to fix panic on help message (`./bin/manager --help`).
Running `bin/manager --help` should output:
```
Usage of bin/manager:
-alsologtostderr
log to standard error as well as files
-config string
The name of the ConfigMap to load the operator configuration from. If it does not exist, the operator will create and initialise it. (default "codeflare-operator-config")
-kubeconfig string
Paths to a kubeconfig. Only required if out-of-cluster.
-log_backtrace_at value
when logging hits line file:N, emit a stack trace
-log_dir string
If non-empty, write log files in this directory
-log_link string
If non-empty, add symbolic links in this directory to the log files
-logbuflevel int
Buffer log messages logged at …
```
> Prase command line flags

- config/e2e/kustomization.yaml
Follows up #400 to set the namespace at the top-level overlay used by the e2e tests.
> e2e: Fix deployment namespace

- test/e2e/install-codeflare-sdk.sh
- test/e2e/mnist_raycluster_sdk_test.go
- test/e2e/support.go
closes https://github.com/project-codeflare/codeflare-operator/issues/250
Updated the test `TestMNISTRayClusterSDK` to use poetry for installing CodeFlare SDK by replacing pip
Added the script `install-codeflare-sdk.sh` for installing codeflare-sdk using poetry and can reuse this in another tests
> Update SDK e2e test to reflect poetry changes

- test/e2e/mnist_raycluster_sdk.py
N/A
Related to slow environment issues detected in https://github.com/opendatahub-io/codeflare-operator/pull/31
Raise a timeout in SDK e2e test Python script to accommodate slower environment.
N/A
Could be verified by running `TestMNISTRayJobMCADRayCluster` on slower environment.
> Raise SDK e2e test timeout in Python script

- .github/workflows/tag-and-build.yml
Fixes https://github.com/project-codeflare/codeflare-operator/issues/417
Create  PR in OpenShift community operators repository as a last step, after operator release is published on GH.
Close PR with dependency and Readme changes in case waiting step fails or is cancelled.
Delete PR branch in any case if it was created.
Can be verified by running release workflow against own repository.
> Adjust release GH workflow to handle error cases

- .github/workflows/e2e_tests.yaml
If e2e test fails on merged commit then a message is sent to `codeflare-nightlies` Slack channel.
N/A
Verified manually.
> Send notification on Slack if e2e fails on push event

- test/upgrade/olm_upgrade_test.go
Fixes https://github.com/project-codeflare/codeflare-operator/issues/426
This PR makes sure that Job created by AppWrapper is suspended, resumed by `TestMNISTCheckAppWrapperStatus`. As a result the upgrade test is not dependent on operator upgrade timing, as upgraded operator is running when `TestMNISTCheckAppWrapperStatus` is invoked.
Verified by running upgrade e2e test.
> Adjust upgrade e2e test to pause Job before upgrade

- go.mod
N/A
Remove unnecessary replace line in go.mod file brought by https://github.com/project-codeflare/codeflare-operator/pull/428
N/A
> Remove MCAD replace line in go.mod

- .github/workflows/e2e_tests.yaml
- .github/workflows/olm_tests.yaml
Closes https://github.com/project-codeflare/codeflare-operator/issues/436
Storing all KinD pod logs as PR check job artifact.
Check PR check job artifacts - all KinD pod logs are stored there.
> e2e tests: Export all KinD logs

- .github/workflows/tag-and-build.yml
- Makefile
N/A
Remove alignment of go.mod dependencies from image build. Now the alignment will be done only for operator release.
Current behavior broke dev image build - https://github.com/project-codeflare/codeflare-operator/actions/workflows/operator-image.yml
Run `make build`.
> Fix MCAD version in Makefile

- config/manifests/bases/codeflare-operator.clusterserviceversion.yaml
During release, the community-operators-prod sync is failing [with](https://github.com/project-codeflare/codeflare-operator/blob/main/config/manifests/bases/codeflare-operator.clusterserviceversion.yaml#L5):
```
[static-tests : run-suite]     {
[static-tests : run-suite]       "type": "error",
[static-tests : run-suite]       "message": "CSV contains an invalid value for metadata.annotations.alm-examples",
[static-tests : run-suite]       "check": "check_required_fields"
[static-tests : run-suite]     },
```
this is due to the following [check](https://github.com/redhat-openshift-ecosystem/operator-pipelines/blob/main/operator-pipeline-images/operatorcert/static_tests/community/bundle.py#L184C36-L184C44):
```
("metadata.annotations.alm-examples", re.compile(r".{30,}", re.DOTALL), True), …
```
> update: change CSV alm-examples to ''

- config/manifests/bases/codeflare-operator.clusterserviceversion.yaml
During release, the community-operators-prod sync is failing [with](https://github.com/project-codeflare/codeflare-operator/blob/main/config/manifests/bases/codeflare-operator.clusterserviceversion.yaml#L5):
```
[static-tests : run-suite]     {
[static-tests : run-suite]       "type": "error",
[static-tests : run-suite]       "message": "CSV contains an invalid value for metadata.annotations.alm-examples",
[static-tests : run-suite]       "check": "check_required_fields"
[static-tests : run-suite]     },
```
this is due to the following [check](https://github.com/redhat-openshift-ecosystem/operator-pipelines/blob/main/operator-pipeline-images/operatorcert/static_tests/community/bundle.py#L184C36-L184C44):
```
("metadata.annotations.alm-examples", re.compile(r".{30,}", re.DOTALL), True), …
```
> update: change CSV alm-examples

- test/e2e/kind.sh
Related to: https://issues.redhat.com/browse/RHOAIENG-2058 
Map Host Port 80 to Container Port 80 in KinD Setup. Required for usage against CodeFlare-SDK e2e test.
e2e tests should continue to pass.
> Add Host to Container port mapping for KinD Cluster

- test/e2e/kind.sh
N/A
Cherrypicking https://github.com/project-codeflare/codeflare-common/pull/31 to apply change for manual KinD provision for manual tests.
Run `make kind-e2e` and check that Ingress is properly deployed.
> Raise KinD Ingress controller version to v1.9.6 for manual setup

- .github/workflows/odh-notebooks-sync.yml
- .github/workflows/project-codeflare-release.yml
[https://issues.redhat.com/browse/RHOAIENG-2341](https://issues.redhat.com/browse/RHOAIENG-2341)
Add step to sync ODH notebooks with Codeflare-SDK release by creating automated PR for Project-Codeflare-notebooks repository with latest Cddeflare-SDK release version
A test run in fork results in the following automated PR changes :
[Successful test build ](https://github.com/abhijeet-dhumal/codeflare-operator/actions/runs/7800070867/job/21272132238#step:7:51)
[Generated automated test PR](https://github.com/sutaakar/notebooks/pull/6)
[Incase codeflare-sdk version doesn't exist](https://github.com/abhijeet-dhumal/codeflare-operator/actions/runs/7844005930/job/21405489057#step:6:80)
> add step to sync ODH notebooks with Codeflare-SDK release

- .github/workflows/mnist-job-test-image.yml
- Makefile
- test/pytorch_mnist_image/Dockerfile
- test/pytorch_mnist_image/download_dataset.py
- test/pytorch_mnist_image/entrypoint.sh
- test/pytorch_mnist_image/mnist.py
- test/pytorch_mnist_image/mnist_pip_requirements.txt
[RHOAIENG-2617](https://issues.redhat.com/browse/RHOAIENG-2617)
Generating MNIST test job image to be used in e2e tests. This image doesn't need any external dependency.
Tests adjustments will follow once this PR is merged and image is built and pushed.
Serves as a replacement for https://quay.io/repository/project-codeflare/mnist-job-test?tab=tags version 0.0.1
Test it manually using `make image-mnist-job-test-push`.
> Prepare Pytorch MNIST test image for disconnected testing

- .github/workflows/e2e_tests.yaml
- .github/workflows/mnist-job-test-image.yml
- .github/workflows/olm_tests.yaml
- .github/workflows/operator-image.yml
- .github/workflows/precommit.yml
- .github/workflows/tag-and-build.yml
- .github/workflows/unit_tests.yml
- .github/workflows/verify_generated_files.yml
https://issues.redhat.com/browse/RHOAIENG-2615
Updated versions of all GitHub actions to use Node 20.
N/A
> Update deprecated GitHub actions

- .github/workflows/project-codeflare-release.yml
Display KubeRay parameter in release workflow and check for the existence of the chosen KubeRay release.
Previously the KubeRay parameter was not displayed
> Display input for KubeRay parameter and check for existence

- test/e2e/instascale_machinepool_test.go
https://github.com/project-codeflare/instascale/issues/143
These changes are to align the instascale machinepool tests with https://github.com/project-codeflare/instascale/pull/182. As opposed to checking for a specific machinepool ID the tests now check for the existence of a machinepool with a label key matching that of the appwrapper name.
This also relies on updating the codeflare-common repo with this [pr](https://github.com/project-codeflare/codeflare-common/pull/15)
> test: update machinepool tests to identify machines based on label

- test/e2e/mnist.py
- test/odh/resources/mnist.py
By reducing number of epochs and number of training samples in each epoch it was possible to reduce
test execution time of single test from more than 10 minutes to less than 2 minutes.
https://issues.redhat.com/browse/RHOAIENG-3771
> RHOAIENG-3771 - Reduce execution time of E2E tests

- Makefile
Issue: https://issues.redhat.com/browse/RHOAIENG-4765 
TLDR:
> go: sigs.k8s.io/controller-runtime/tools/setup-envtest@latest (in sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20240322145600-aeef2b60d6f7): go.mod:3: invalid go version '1.22.0': must match format 1.23
This PR provided ideas for the fix: https://github.com/KusionStack/operating/pull/169 
We are currently using the `latest` version of the mentioned dependency. 
This PR is setting it to the latest release that works with our current go version `1.20` until we can upgrade to `go1.22`
- e2e tests should pass on this PR.
> Fix e2e test - invalid go version error

- .github/workflows/olm_tests.yaml
- config/e2e/config.yaml
- config/e2e/kustomization.yaml
- main.go
- pkg/config/config.go
- test/e2e/setup.sh
> Disable MCAD by default

- .github/workflows/e2e_tests.yaml
- go.mod
- main.go
- pkg/controllers/raycluster_controller.go
- pkg/controllers/support.go
Issue: https://issues.redhat.com/browse/RHOAIENG-1056 
- Refactor the ingress/route creation and TLS support to the RayCluster Controller in the CFO.
- Added creation of rayclient route OpenShift, rayclient ingress and ingresses for KinD/vanilla clusters.
- RayCluster Controller to always run alongside the CFO.
- Adjusted e2e tests to disable OAuth in the CFO config, using this config bool value to indicate to the RayCluster Controller whether to create a secure route and OAuth resources on OpenShift or an ingress for KinD clusters (for e2e tests).
- Created a support package and several functions including:
- `createRayClientRoute`
- `createRayClientIngress`
- `createIngressApplyConfiguration`
- `isOnKindCluster`
- `getClusterType`
- `annotationBoolVal`
- `getIngressDomain`
This PR …
> Refactor creation logic of ingress/routes into RayCluster Controller

- .github/workflows/project-codeflare-release.yml
- .github/workflows/tag-and-build.yml
Removed InstaScale & MCAD from release process
> Removed InstaScale & MCAD from release workflow

- config/crd/kustomization.yaml
- config/default/kustomization.yaml
backport fix from https://github.com/opendatahub-io/codeflare-operator/pull/49
> fix(manifests): remove emptry CRD and reference

- .github/workflows/olm_tests.yaml
N/A
Removing test execution from OLM upgrade test.
Considering that current operator is no longer a standalone component it doesn't have sense to run e2e tests for it.
This OLM test is adjusted to verify that it is possible to upgrade existing OLM operator with newly built operator, making sure that upgrade process itself pass.
> Fix OLM upgrade test

- main.go
- pkg/controllers/raycluster_controller.go
- pkg/controllers/support.go
Jira: https://issues.redhat.com/browse/RHOAIENG-5333 
- In the support file, we are separating concerns between what is needed for OpenShift and KinD clusters. I.e., `ingressHost` is only required for ingresses.
- Added `isOpenShiftInitalized` variable - Its purpose is to ensure that when checking if the cluster type is `OpenShift`, this check and call to the DiscoveryAPI is only performed once.
- Accessing KubeRay configuration directly.
**Overall functionality remains the same.**
**On OpenShift:**
1. Login to your OpenShift cluster.
2. Run KubeRay v1.1.0 - [Install doc](https://docs.ray.io/en/master/cluster/kubernetes/getting-started/raycluster-quick-start.html#:~:text=kindest/node%3Av1.26.0-,Step%202%3A%20Deploy%20a%20KubeRay%20operator,-%23)
3. Run the CFO locally against the cluster …
> RC Controller - Avoid multiple calls to DiscoveryAPI

- .github/workflows/e2e_tests.yaml
- config/e2e/config.yaml
- config/e2e/kustomization.yaml
This (re-)adds the ConfigMap used for e2e tests, instead of monkey patching the operator code.
> Add a ConfigMap for e2e tests

- config/e2e/config.yaml
- main.go
- pkg/config/config.go
- pkg/controllers/raycluster_controller.go
- pkg/controllers/support.go
Rayclient Route to resolve its own ingress domain, and enable local_interactive by default
Jira: https://issues.redhat.com/browse/RHOAIENG-5330 
- Set local_interactive feature to be always enabled by default.
- RayClient Route now resolves its own `ingress domain` based on the route's name and namespace.
- Removed unused `annotationBoolVal()`
- Add `ingressDomain` field to CFO configmap: This field has `fake.domain` set as default and is used for the generation of the full rayclient client and dashboard ingress hosts. I.e., `ray-dashboard-<clusterName>-<namespace>.fake.domain` or `rayclient-<clusterName>-<namespace>.fake.domain`. For the e2e workflow, the ingressDomain is set to "kind".
> Fix and enable local_interactive feature by default

- .github/workflows/e2e_tests.yaml
N/A
Deploying Kuberay before CodeFlare operator, as CodeFlare operator needs Kuberay CRDs to start.
Verified by PR check - CodeFlare operator log contains entries related to Ray Cluster resources creation.
> E2E tests: Deploy Kuberay before starting CodeFlare operator

- pkg/controllers/support.go
- test/e2e/mnist_rayjob_raycluster_test.go
N/A
Adjusted existing e2e test to use Ingress/Route created by operator to download job logs.
Currently the test doesn't work on OpenShift because oauth container is still created by SDK. Once oauth creation is part of operator then it should work on OpenShift.
Verified by running PR check. Manual verification limited due to OpenShift issues.
Can be verified by running e2e test against fully deployed KinD cluster with Kuberay and operator.
> Use Dnsmasq to provide DNS for KinD

- config/manager/params.env
introduced in change https://github.com/opendatahub-io/codeflare-operator/commit/afe5bdc7fb34bddc72bbc8e177d31eaa9fb32bde
cause error:
`* field specified in var '{namespace ConfigMap.v1.[noGrp] {data.namespace}}' not found in corresponding resource`
which prevent deployment in ODH operator
> fix(manifests): missing namespace in CM stack-config

- pkg/controllers/raycluster_controller.go
An owner reference from a non-namespaced resource cannot be namespaced.
> Remove owner reference for ClusterRoleBinding to RayCluster

- .github/workflows/component_tests.yaml
- Makefile
- pkg/controllers/raycluster_controller_test.go
- pkg/controllers/suite_test.go
N/A
It initially started as a simple test adjustment. It ends up....
Created GH workflow executing the component tests.
Rewrote the tests to use go lang k8s client. Fix various issues and errors in tests.
Adjusted `getClusterType` to remove unnecessary code.
Tests can be executed using `make test-component`.
> Adjust env tests for RayCluster controller

- .github/workflows/component_tests.yaml
- .github/workflows/e2e_tests.yaml
- .github/workflows/mnist-job-test-image.yml
- .github/workflows/olm_tests.yaml
- .github/workflows/operator-image.yml
- .github/workflows/precommit.yml
- .github/workflows/tag-and-build.yml
- .github/workflows/unit_tests.yml
- .github/workflows/verify_generated_files.yml
This does not change the go version, but means that when we do change it in go.mod we don't have to manually change all the GitHub workflows.
> Get go version for setup-go action from go.mod file

- CONTRIBUTING.md
- README.md
- config/manifests/bases/codeflare-operator.clusterserviceversion.yaml
- main.go
Cleanup a few MCAD/InstaScale references missed in c771aae4.
> Remove dangling MCAD and InstaScale references

- .github/workflows/olm_tests.yaml
N/A
OLM PR check is broken due to operator creating oauth resources by default. For KinD the oauth needs to be disabled.
Run PR check.
> Fix OLM PR check by creating ConfigMap disabling oauth

- pkg/controllers/raycluster_controller.go
[RHOAIENG-6385](https://issues.redhat.com/browse/RHOAIENG-6385)
Replaced hard coded ports for the Ray Cluster Network Policy with label selectors that will allow traffic to and from the head & worker pods.
* Ensure the Codeflare Operator is not installed on your cluster.
* Clone the repo locally and clone this branch
* Run `make image-build -e IMG=quay.io/<quay-user>/<repo>:<tag>`
* Run `make image-push -e IMG=quay.io/<quay-user>/<repo>:<tag>`
* Run `make deploy IMG=quay.io/<quay-user>/<repo>:<tag>`
Run through the [job client demo](https://github.com/project-codeflare/codeflare-sdk/blob/main/demo-notebooks/guided-demos/2_job_client.ipynb) with SDK v0.16.0
Ensure the example job succeeds 
> Altered network policy to allow all trafic for head & worker pods

- Dockerfile
- Makefile
- main.go
https://issues.redhat.com/browse/RHOAIENG-118
Fix Unknown build info in CodeFlare operator log
To test this PR you should modify Dockerfile, build your own image and add it to DSC
1. In the Dockerfile, add the following two lines to retrieve the BUILD_VERSION variable from your Git repository:
```
COPY .git .git
RUN git config --global --add safe.directory /workspace
```
2. build the image using new makefile command:  `docker build -t quay.io/username/imagename:tag` .If running on macOS, use: `docker build --platform linux/amd64 -t quay.io/username/imagename:tag `
3. push your docker image to your [quay.io](http://quay.io/) account
4. add your custom image to **config/manager/params.env**  and push your changes to github
5. Inside your cluster, navigate to **'rhods'** under …
> Fix Unknown build info in CodeFlare operator log

- config/e2e/config.yaml
- main.go
- pkg/config/config.go
- pkg/controllers/raycluster_webhook.go
[RHOAIENG-6505](https://issues.redhat.com/browse/RHOAIENG-6505)
I updated the CFO config to include an image to be used for cert creation in the init containers added by the CFO webhook. This is added so that in the case of a disconnected cluster there is not an extra image required.
- Install CodeFlare Operator from this branch, and provide a custom image in the `codeflare-operator-config` configMap adding the image to the kuberay configuration like this:
```
kuberay:
ingressDomain: ""
mTLSEnabled: true
rayDashboardOAuthEnabled: true
certGeneratorImage: "registry.access.redhat.com/ubi9@sha256:770cf07083e1c85ae69c25181a205b7cdef63c11b794c89b3b487d4670b4c328"
```
- Restart the CFO pod.
- Create a raycluster using a demo notebook, and check that the init containers are using the image …
> Allow for custom CertGeneratorImage

- Makefile
- Commented out make install/uninstall targets as not required. We should revert this commit once AppWrapper CRDs are required and available to install from our repository.
Run `make install`.
> Comment out install/uninstall make targets

- Makefile
- scripts/setup-kueue-resources.sh
Added a script for creation of Kueue related resources
Delete all of your Kueue related resources Cluster Queue, Resource Flavor, Local Queues and run
`make kueue-setup`
You will be prompted for resources and other aspects of your Kueue resources.
Note: For memory you must actually enter the unit as well as the number e.g.
```
Enter your Cluster Queue Memory (The amount of memory available) (default:  [60Gi] ):  250Gi
```
> Added kueue setup make target

- config/e2e/config.yaml
- test/e2e/kind.sh
https://issues.redhat.com/browse/RHOAIENG-7055
Exposing HTTPS endpoint on KinD to be able to test gRPC calls.
N/A
> Enable mTLS for e2e tests and HTTPS for KinD cluster

- main.go
Jira: https://issues.redhat.com/browse/RHOAIENG-8274 
- CertGeneratorImage to reference registry.redhat.io
- If the CodeFlare-Operator was previously installed, please delete the `codeflare-operator-config` configmap before re-installing.
- Install CodeFlare-Operator from this branch
- Create a raycluster using a demo notebook, and check that the init containers are using the image specified in the configmap and that the raycluster pods are created succesfully. 
> CertGeneratorImage to reference registry.redhat.io

- config/e2e/config.yaml
- go.mod
- go.sum
[RHOAIENG-6450](https://issues.redhat.com/browse/RHOAIENG-6450)[RHOAIENG-6450](https://issues.redhat.com/browse/RHOAIENG-6450)
Updated e2e cert generator image to use the new Ray image `quay.io/project-codeflare/ray:2.20.0-py39-cu118`
Run the SDK E2E tests using this PR CFO side and this [PR](https://github.com/project-codeflare/codeflare-sdk/pull/530) SDK side 
> Updated e2e cert generator image

- CONTRIBUTING.md
https://issues.redhat.com/browse/RHOAIENG-8763
I've added an e2e basic dev workflow for a new contributor to follow
> Add example dev workflow to CONTRIBUTING.md

- config/e2e/config.yaml
- go.mod
- go.sum
- test/e2e/mnist_pip_requirements.txt
- test/e2e/mnist_rayjob_raycluster_test.go
- test/odh/resources/requirements.txt
> Update TLS certificate generation container image

- config/rbac/role.yaml
- main.go
- pkg/controllers/raycluster_controller.go
- pkg/controllers/support.go
I've added watches for owned resources so that the controller will automatically re-reconcile on updates to owned resources. I've also added a label to the CRB make mapping from CRB to RayCluster resource possible
> add watches for owned resources and CRBs

- .github/workflows/e2e_tests.yaml
- Dockerfile
- config/e2e/patch_resources.yaml
- test/e2e/mnist.py
- test/e2e/mnist_pytorch_appwrapper_test.go
- test/e2e/mnist_rayjob_raycluster_test.go
- test/e2e/setup.sh
[RHOAIENG-9004](https://issues.redhat.com/browse/RHOAIENG-9004)
Adjust GitHub e2e workflow to setup and install NVidia operator.
Convert Ray tests to use MNIST fashion test case on GPU. Adjust `TestMNISTPyTorchAppWrapper` to use GPU.
As a workaround for having just one GPU the tests are executed sequentially.
I also had to alter uploading CFO image to be loaded by KinD CLI.
The reason is that GPU image uses Docker and doesn't interact well with locally created registry.
Edit:
Thinking whether we should add GPU tests next to existing nonGPU ones, or rather replace them. Having both will increase number of tests, on the other side non GPU tests are faster and can be ran anywhere.
Run e2e PR check - GPU is made available on KinD cluster and tests use it.
> [RHOAIENG-9004] Adjust existing test and workflow for GPU testing

- .github/workflows/e2e_tests.yaml
> Run only GPU tests for PR check

- .github/workflows/project-codeflare-release.yml
- config/e2e/config.yaml
- config/e2e/patch_resources.yaml
- main.go
- pkg/config/config.go
- pkg/controllers/raycluster_webhook.go
- pkg/controllers/raycluster_webhook_test.go
- pkg/controllers/support.go
https://issues.redhat.com/browse/RHOAIENG-8552
I've made the cert generator image and oauthproxy image build time configurable
run operator and verify that the images specified via make build are respected in the resulting RayCluster
There was also discussion about making these configurable at deployment time. I think the only difference would be whether we would need to re-release CFO to update the vs the RHODS/ODH operator. I lean towards leaving it on our end via build args but I'm open to suggestions
> make oauth image and cert generator image configurable via env vars

- test/e2e/mnist_pytorch_appwrapper_test.go
- test/e2e/mnist_rayjob_raycluster_test.go
Expand e2e tests to verify that resource deletion is successful.
Side reason for this change is to make sure e2e tests are stable as it seems that deleting Workload resources, local queue and namespace at the same time can lead to race condition when ClusterQueue is not properly updated, causing Workloads to hang.
Verified by running e2e tests locally.
> Adjust e2e tests to verify deletion of resources

- .github/workflows/e2e_tests.yaml
If CFO deployment fails for some reason, then no logs are uploaded in PR check artifacts.
That makes PR check issue analysis much harder. Logs are always useful.
N/A
> Upload KinD pod logs even when CFO deployment fails

- pkg/controllers/raycluster_controller.go
- pkg/controllers/raycluster_controller_test.go
[https://issues.redhat.com/browse/RHOAIENG-9247](https://issues.redhat.com/browse/RHOAIENG-9247)
Added a check for imagePullSecrets in the head pod, and if it does not exists delete the head pod, so it can be redeployed.
Set up an integrated OpenShift container registry and upload an image to it:
[https://github.com/opendatahub-io/distributed-workloads/tree/main/images/runtime/examples#readme](https://github.com/opendatahub-io/distributed-workloads/tree/main/images/runtime/examples#readme)
Use the uploaded image inside the notebooks, head pod should not enter the ImagePullBackOff state (happens only frequently but not always).
> Add a check for head pod imagePullSecrets

- pkg/controllers/raycluster_webhook_test.go
Creating own copy of RayCluster CR for every negative unit test to make sure they don't affect each other.
Run unit tests.
> Make sure that negative unit tests use own fork of RayCluster CR

- go.mod
- main.go
- pkg/controllers/support.go
The `codeflare-operator` log is littered with update conflict errors such as:
```2024-07-24T13:06:33Z    ERROR   Reconciler error        {"controller": "AppWrapper", "controllerGroup": "workload.codeflare.dev", "controllerKind": "AppWrapper", "AppWrapper": {"name":"kevin1-team-hw","namespace":"kevin1-team"}, "namespace": "kevin1-team", "name": "kevin1-team-hw", "reconcileID": "b6e57167-a357-4c67-85d1-f455e2b57ab6", "error": "Operation cannot be fulfilled on appwrappers.workload.codeflare.dev \"kevin1-team-hw\": the object has been modified; please apply your changes to the latest version and try again"}```
These update conflicts result from trying to update stale Kubernetes object revisions in etcd when multiple reconciliers (or users) are concurrently working on cached copies of these …
> Downgrade StatusReasonConflict errors to debug messages

- pkg/controllers/raycluster_controller.go
- pkg/controllers/support.go
I created a helper function for creating OwnerReferences from RayClusters
> keepin it DRY with a helper function 4 owner ref

- test/e2e/setup.sh
Fixes following errors. Service for webhook is not available immediately: error appears Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.115.38:443: connect: connection refused
> Add sleep before creating Kueue resources

- main.go
- pkg/controllers/raycluster_controller.go
- pkg/controllers/raycluster_webhook.go
- pkg/controllers/raycluster_webhook_test.go
- pkg/controllers/support.go
https://issues.redhat.com/browse/RHOAIENG-10129
created a function which takes a string and appends the controller name to it then hashes it to use as a suffix for the resources created by this controller to avoid naming conflicts
> add hash to end of resource names to avoid name clash

- config/rbac/role.yaml
- pkg/controllers/appwrapper_controller.go
The codeflare operator needs permission to read and write clusterqueues to enable the AppWrapper controller to adjust the lending limit of a designated slack cluster queue to reflect cordoned nodes.
> RBAC fix to enable slack cluster queue lending limit adjustment

- .github/workflows/e2e_tests.yaml
- config/e2e/patch_resources.yaml
[RHOAIENG-12186](https://issues.redhat.com/browse/RHOAIENG-12186)
Updating the cert generator image used by the E2E tests to align with updated images.
Ensure that the E2E tests run successfully.
> Update cert generator image to Ray 2.35

- go.mod
- go.sum
- test/e2e/mnist_pytorch_appwrapper_test.go
- test/e2e/mnist_rayjob_raycluster_test.go
- test/e2e/setup.sh
- test/e2e/support.go
[RHOAIENG-11047](https://issues.redhat.com/browse/RHOAIENG-11047)
Since we are adjusting e2e tests to run with AMD gpu, thus 
- Adding creation of kueue resources as part of test to make it compatible with gpuresources (which is covered in next PR)
- Removing creation of kueue resources  from setup script
- Adjust methods with updated Ray cluster client
Run test manually 
`go test -timeout 30m -v ./test/e2e -run TestMnistPyTorchAppWrapperCpu`
> Add creation of kueue resources in e2e tests

- Dockerfile
N/A
Use Red Hat Go toolset image for CodeFlare operator image build.
E2E tests with built operator image pass.
> Use Red Hat Go toolset image for CodeFlare operator image build

- test/e2e/mnist_pytorch_appwrapper_test.go
- test/e2e/mnist_rayjob_raycluster_test.go
- test/e2e/support.go
Remove creationTimestamp from marshalled template for AppWrapper. This creationTimestamp is brought by marshaller (it is not omitted because it is defined as struct instead of pointer in k8s API). This field breaks Kueue reconciliation in AppWrapper for Kueue 0.8.3.
The change was verified in https://github.com/project-codeflare/codeflare-operator/pull/628
> AppWrapper e2e: Remove creationTimestamp from marshalled template

- .github/workflows/e2e_tests.yaml
- Makefile
Current changes in NVidia GitHub image and `codeflare-common` caused issues in building CFO image in NVidia GitHub image. Adding `--cgroup-manager cgroupfs` helps avoiding the error.
Solution taken from https://github.com/containers/podman/issues/6368 .
Tested in PR check https://github.com/project-codeflare/codeflare-operator/pull/634
> Add --cgroup-manager cgroupfs for e2e PR check

- go.mod
- go.sum
- test/e2e/mnist.py
- test/e2e/mnist_pip_requirements.txt
- test/e2e/mnist_rayjob_raycluster_test.go
Updating e2e tests to work with newest Ray images.
Tested by running PR check.
> E2E tests: Upgrade MNIST test script dependencies

- main.go
When AppWrappers are enabled, it is not correct to configure the controller-runtime cache with a filter that only allows services, secrets, etc with the RayCluster label to be cached. This breaks any AppWrapper that contains one of these resource kinds.
>  Fix improper controller-runtime cache configuration

- config/webhook/manifests.yaml
- pkg/controllers/raycluster_webhook.go
Adds UPDATE to the list of operations on which the `RayCluster` `Mutating Webhook`  operates on. 
This allows to  `oc apply -f ` or `oc replace` to work and gives the ability to update existing running `rayclusters` without deleting them.
Redeploy the mutating webhook and create, update and delete rayclusters and re-create them.
> Adds UPDATE to the RayCluster Mutating Webhook so apply can be used

- test/e2e/deployment_appwrapper_test.go
- test/e2e/job_appwrapper_test.go
- test/e2e/mnist_rayjob_raycluster_test.go
- test/e2e/support.go
Follow up from #640  -- added two additional e2e tests for AppWrappers.  The Deployment+Service one would have failed before the fix.
> add e2e tests for AppWrappers with Jobs, Deployments, and Services

- .github/workflows/e2e_tests.yaml
Existing GPU runner references Ubuntu version in its name even though it is unrelated with GPU runner image.
Renaming the runner to a name corresponding to the runner image name.
> Rename GPU GitHub runner to avoid version confusion

- .github/workflows/olm_tests.yaml
Ubuntu 20.04 image will become deprecated and removed in couple of months.
We need to migrate to newest version to keep PR checks running.
OLM PR check is passing.
> Migrate GitHub runners to newest Ubuntu

- .github/workflows/e2e_tests.yaml
- go.mod
- go.sum
- pkg/controllers/raycluster_controller.go
- pkg/controllers/raycluster_controller_test.go
- test/e2e/mnist_rayjob_raycluster_test.go
https://github.com/project-codeflare/codeflare-operator/issues/649
Delete Ray cluster head pod only if user doesn't specify own imagePullSecrets and imagePullSecrets from OAuth ServiceAccount are not present in the head Pod.
Depends on https://github.com/project-codeflare/codeflare-common/pull/89
Newly added tests are passing (checked by PR check)
> Don't delete Ray head Pod when ImagePullSecret is provided

- .github/workflows/project-codeflare-release.yml
https://issues.redhat.com/browse/RHOAIENG-16074
Added automated update step for component metadata file in workflow
> Add automated update step for component metadata file in workflow

- pkg/controllers/raycluster_controller.go
- pkg/controllers/raycluster_controller_test.go
Use RayCluster `spec.suspend` field to detect that Ray cluster was admitted and oauth resources should be created.
Previous `status.state` field isn't usable any more as newer KubeRay version set state once Ray pods are up and running.
Verified manually against OCP.
> Create oauth objects when RayCluster spec suspend is false

- Makefile
- config/crd/appwrapper/kustomization.yaml
- config/crd/crd-appwrapper.yml
- config/rbac/role.yaml
- go.mod
- go.sum
- pkg/controllers/appwrapper_controller.go
Features
+ Propagate SchedulingGates in RunWithPodSetsInfo
+ extend PodSets() to compute TopologyRequest
+ Support PreferNoSchedule labels for AutoPilot
+ Implement PodSet inference for JobSet
Bugs and Regressions
+ move appwrapper finalizer injection from defaulting webhook to controller
+ use ptr.Equal to validate managedBy is immutable
+ fix handling of labels/annotations in utils.GetPodTemplateSpec
> Upgrade AppWrapper from v1.0.0 to v1.0.4

- go.mod
- go.sum
- test/e2e/mnist_rayjob_raycluster_test.go
Running e2e tests locally.
Adding constant namespace names to tests that require to add the ray dashboard URL to `/etc/hosts`. This way, we can run the e2e tests locally by pre-setting the host before running the tests.
PR: https://github.com/project-codeflare/codeflare-common/pull/93
> Add constant namespaces for RayDashboard tests

- Makefile
- README.md
- test/e2e/kind.sh
Jira : https://issues.redhat.com/browse/RHOAIENG-19986
Please go through the instructions in the readme.
> Update readme and the Makefile to remove outdated instructions and adjust the local test timeouts

- .github/workflows/project-codeflare-release.yml
- .github/workflows/update-release-matrix-to-confluence.yml
closes https://issues.redhat.com/browse/RHOAIENG-16512
- Added workflow for adding distributed workloads release matrix info to confluence DW Release details page
- Validated workflow to handle , if Release versions is upgrading for existing RHOAI release version table to update the new release version details
> Add Github Action workflow for updating DW Components Release matrix info to confluence 

- .github/workflows/e2e_tests.yaml
- go.mod
- go.sum
- test/e2e/deployment_appwrapper_test.go
- test/e2e/job_appwrapper_test.go
- test/e2e/mnist_pytorch_appwrapper_test.go
- test/e2e/mnist_rayjob_raycluster_test.go
Closes [RHOAIENG-11047](https://issues.redhat.com/browse/RHOAIENG-11047)
1. Add codeflare-operator e2e tests to run with AMD gpu and AMD ROCm Ray base container image
2. Removes usage of `numberofGpus` parameter from createClusterQueue, constructRayCluster and constructRayJob method
Manually run the tests on OCP with NVIDIA and AMD gpus 
> Add AMD GPU test  for ray clusters

- go.mod
- go.sum
To pick up https://github.com/project-codeflare/codeflare-common/pull/88
> update codeflare-common import

- pkg/controllers/raycluster_controller.go
Enable auto-detection of the namespace where
kuberay-operator is deployed so we can enable network traffic between raycluster namespace and kuberay-operator namespace.
[RHOAIENG-22373](https://issues.redhat.com/browse/RHOAIENG-22373 )
auot-detect the namespace where kuberay-operator is deployed to enable correct configuration of network policies for ray clusters
> Auto-Detect kuberay-operator namespace

- pkg/controllers/suite_test.go
https://github.com/project-codeflare/codeflare-operator/issues/684
update file source for Route CRD.
Also fail early if the http request returns a 404 as it did in this case. 
Tests should pass
> update route link as previous file was removed
