- Makefile
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Add stub unit-test for OpenShift-CI setup

- Makefile
- OWNERS
> Format OWNERS file

- .golangci.yaml
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Increase timeout for golangci

- Dockerfile
- Makefile
- bundle.Dockerfile
- bundle/manifests/codeflare-operator-controller-manager-metrics-service_v1_service.yaml
- bundle/manifests/codeflare-operator-manager-config_v1_configmap.yaml
- bundle/manifests/codeflare-operator-manager-edit-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- bundle/manifests/codeflare-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/codeflare-operator.clusterserviceversion.yaml
- bundle/manifests/codeflare.codeflare.dev_instascales.yaml
- bundle/manifests/codeflare.codeflare.dev_mcads.yaml
- bundle/manifests/mcad.ibm.com_appwrappers.yaml
- bundle/manifests/mcad.ibm.com_queuejobs.yaml
- bundle/manifests/mcad.ibm.com_schedulingspecs.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/manager/manager.yaml
- config/manifests/bases/codeflare-operator.clusterserviceversion.yaml
I will be submitting this PR (or a very very similar one) to the community operatorhub repo
> Operator hub onboarding

- api/v1alpha1/mcad_types.go
- config/crd/bases/codeflare.codeflare.dev_mcads.yaml
- controllers/mcad_controller.go
readiness state just reflects the availability of the deployment
closes: #31
> add ready status to MCAD

- api/v1alpha1/mcad_types.go
- config/crd/bases/codeflare.codeflare.dev_mcads.yaml
> Update MCAD crd descriptions

- api/v1alpha1/instascale_types.go
- config/crd/bases/codeflare.codeflare.dev_instascales.yaml
- config/crd/bases/codeflare.codeflare.dev_mcads.yaml
- controllers/instascale_controller.go
- controllers/mcad_controller.go
- controllers/util/util.go
depends on: #65 
closes: #32 
I refactored deployment status checking out into its own function.
This includes the changes made in #65 and will be rebased once those changes have been merged.
> Add ready status for instascale

- Makefile
This should have been included in #127 
fyi @sutaakar
> Update version in makefile to 0.0.4

- config/internal/instascale/clusterrole.yaml.tmpl
- controllers/testdata/instascale_test_results/case_1/clusterrole.yaml
Relating to this instascale [PR](https://github.com/project-codeflare/instascale/pull/83)
and this github [issue](https://github.com/project-codeflare/instascale/issues/81).
> Updating rbacs for instascale

- config/internal/instascale/deployment.yaml.tmpl
[linked here in the instascale](https://github.com/project-codeflare/instascale/pull/85)
> refactor: add liveness and readyness probes to instascale deployment

- .github/workflows/tag-and-build.yml
Fixes https://github.com/project-codeflare/codeflare-operator/issues/175, https://github.com/project-codeflare/codeflare-operator/issues/172
> Adjust Makefile versions before building operator image

- controllers/mcad_controller.go
https://github.com/project-codeflare/codeflare-operator/blob/main/controllers/mcad_controller.go#L232 has added resource
> Update: remove duplicated resource and should have lower in order

- test/support/ray.go
Return back WriteRayJobLogs function which will retrieve Ray Job id from RayJob CR and use Ray REST API to retrieve logs for this job to be stored.
N/A
> Test support: Return WriteRayJobLogs function

- .github/workflows/tag-and-build.yml
Minor adhoc adjustment for release process, no issue created.
Adjusted replacement commands in release workflow to be able to replace any value.
It is needed as https://github.com/project-codeflare/codeflare-operator/pull/246 and https://github.com/project-codeflare/codeflare-operator/pull/265 changes format of existing versions in Makefile.
currently N/A, can be tested by manually executing this workflow, but that requires additional adjustments due to GVK changes for CRs.
> Release workflow - replace any version value in Makefile

- CONTRIBUTING.md
This pr contains a truly monumental and thoroughly tested alteration of the codeflare-operator codebase. An absolutely spectacular refinement.
> docs: spelling correction

- .github/workflows/tag-and-build.yml
> Edit release wf

- .github/workflows/tag-and-build.yml
Adjusting `sed` commands in release workflow to properly replace any value supplied as version parameter for workflow.
Tested on own fork - https://github.com/sutaakar/codeflare-operator/pull/34
> Release workflow: Update Readme sed commands to process any semver value

- .github/workflows/project-codeflare-release.yml
> remove arg for quay org, IS and MCAD images no longer being built

- test/e2e/mnist_raycluster_sdk_test.go
N/A
Update the reason for skipping SDK e2e test.
> Adjust the SDK PR link as a reason to skip SDK e2e test

- Dockerfile
> Pin ubi image v

- go.mod
- go.sum
> Update GRPC version for CVE

- Makefile
- go.mod
- go.sum
Leverages https://github.com/ray-project/kuberay/pull/1546.
Closes #354.
> Use kuberay/ray-operator@vX.Y.Z Go module

- .github/workflows/tag-and-build.yml
> Removed defaults.go reference

- README.md
Updated the KubRay version in the compatibility matrix.
N/A
> Updated KubeRay version in Readme

- config/rbac/mcad-controller-ray-clusterrolebinding.yaml
Closes [#21](https://github.com/opendatahub-io/codeflare-operator/issues/21)
Changed the `openshift-operators` namespace mention to `system` 
> Changed namespace in MCAD Ray CRB

- .github/workflows/project-codeflare-release.yml
- .github/workflows/tag-and-build.yml
- README.md
Fixes https://github.com/project-codeflare/codeflare-operator/issues/380
Added KubeRay version parameter to overall release workflow.
Can be verified by running the release workflow targeting own organization (to avoid accidentally releasing official repos).
> Add missing KubeRay version parameter for release workflow

- config/manifests/bases/codeflare-operator.clusterserviceversion.yaml
Reverts project-codeflare/codeflare-operator#447
> Revert "update: change CSV alm-examples to ''"

- .github/workflows/project-codeflare-release.yml
Changed ref back to `github.ref`
> Fixed MCAD release

- go.mod
- go.sum
This PR will address a Medium level CVE:
**Introduced through:**
google.golang.org/protobuf@v1.31.0, github.com/golang/protobuf@v1.5.3 and others
**Fixed in:**
google.golang.org/protobuf@1.32.0
> Upgrade protobuf dependency to address CVE

- config/rbac/admin_role.yaml
- config/rbac/editor_role.yaml
- config/rbac/kustomization.yaml
https://issues.redhat.com/browse/RHOAIENG-2184
add an aggregating role to the CFO
make sure that users have ability to create appwrappers in namespaces where they have editor or admin access
> add roles for admin and editor to operator

- README.md
N/A
Updated release instructions to reflect additional work to be done.
N/A
> Update README.md with release instructions

- test/odh/resources/mnist_mcad_mini.ipynb
https://issues.redhat.com/browse/RHOAIENG-2617
Using test image which doesn't need to download anything from internet. This will allow easy test execution in disconnected environment.
> e2e tests: Use test image from quay.io/project-codeflare/demo-images

- .github/workflows/project-codeflare-release.yml
> Fix MCAD release

- .github/workflows/project-codeflare-release.yml
[https://issues.redhat.com/browse/RHOAIENG-2341](https://issues.redhat.com/browse/RHOAIENG-2341)
[https://github.com/project-codeflare/codeflare-operator/pull/460](https://github.com/project-codeflare/codeflare-operator/pull/460)
Fixed incorrect logic in Codeflare-SDK release sync with notebooks
> fixed incorrect logic in Codeflare-SDK release sync with notebooks

- README.md
Added point 6 to build ODH/CFO image
> Update README.md with ODH/CFO build instructions

- test/odh/resources/mnist_mcad_mini.ipynb
N/A
e2e test speed improvement reduced number of iterations. Unfortunately this wasn't reflected in ODH tests.
Run TestMnistPyTorchMCAD in odh folder.
> e2e tests: Fix finishing condition in ODH e2e test

- Makefile
Update kuberay version  to latest in make file which is compatible with Kueue
> Update kuberay version to latest in make file

- .github/workflows/tag-and-build.yml
N/A
`KUBERAY_VERSION` adjustment was accidentally removed from release workflow. Adding it back.
N/A
> Adjust Kuberay dependency in the Makefile

- pkg/controllers/raycluster_webhook.go
> use namespace from ray cluster

- Makefile
> Test auto-merge commit

- Makefile
- go.mod
- go.sum
Upgrading KubeRay to version 1.2.2 and adjusting related dependencies.
> Upgrade KubeRay to 1.2.2

- go.mod
- go.sum
[Jira Issue link](https://issues.redhat.com/browse/RHOAIENG-18783)
Glog dependencies updated to latest version to solve above CVE.
Snyk used locally after change and CVE no longer appears.
> fix: CVE-2024-45339 - update golang/glog

- .github/workflows/project-codeflare-release.yml
> Fix workflow generate-component-metadata step

- OWNERS
[Jira Issue](https://issues.redhat.com/browse/RHOAIENG-22446)
OWNERS file updated with new Training Ray team members
> task(RHOAIENG-22446): Updated OWNERS with Ray Team

- README.md
[RHOAEING-25519](https://issues.redhat.com/browse/RHOAIENG-25519)
Manually update CodeFlare Compatibility matrix
N/A
> task(RHOAIENG-25519): Update CodeFlare Compat Matrix

- README.md
[Jira Link](https://issues.redhat.com/browse/RHOAIENG-27838)
Manually updating compat matrix as workflow doesn't need to be invoked this release.
N/A
> task(RHOAIENG-27838): Update CodeFlare Compat matrix
